name: build

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
    tags-ignore:
      - "v*"

jobs:
  build:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run typecheck
#     - name: Lint
#       if: matrix.os == 'ubuntu-latest'
#       run: npm run lint
      - name: Build App
        run: npm run package
        env:
          CI: true
          ELECTRON_WEBPACK_APP_TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      - name: Prepare artifacts
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p artifacts
          mv release/build/{*.exe,*.deb,*.AppImage,*.dmg} artifacts || true
      - name: Prepare Windows artifacts
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p artifacts
          mv release/build/*.exe artifacts || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: artifacts/
          if-no-files-found: warn
